name: CI/CD Pipeline

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify your node version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Only run this if the build job succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Deploy to a hosting platform (e.g., GitHub Pages, AWS, Heroku)
      - name: Deploy application
        run: |
          echo "Deploying the application..."
          # Add your deployment commands here (e.g., deploy to AWS or GitHub Pages)
